-- Reference: workouts table (run migrations in order for full setup)
-- Columns: id, date, content, created_at, updated_at, assigned_to, assigned_to_group,
-- session, workout_category, pool_size
-- RPC: update_workout, insert_workout (see migrations/20260321000000_workout_save_rpc.sql)
